In [1]:
import numpy as np

In [7]:
a=np.random.randint(10,50, size=(5,2,3),dtype='int8')

In [4]:
a.shape

(5, 2, 3)

In [5]:
a.ndim

3

In [8]:
a.dtype

dtype('int8')

In [9]:
a.size

30

In [10]:
(a.size *8)/8/1024 #number of elements

0.029296875

In [12]:
a.T


array([[[25, 43, 20, 40, 22],
        [13, 34, 37, 19, 48]],

       [[22, 21, 40, 13, 14],
        [44, 41, 21, 46, 48]],

       [[24, 11, 23, 14, 15],
        [17, 33, 35, 28, 39]]], dtype=int8)

In [13]:
a.shape

(5, 2, 3)

In [23]:
a.reshape(2,3,5)

array([[[25, 22, 24, 13, 44],
        [17, 43, 21, 11, 34],
        [41, 33, 20, 40, 23]],

       [[37, 21, 35, 40, 13],
        [14, 19, 46, 28, 22],
        [14, 15, 48, 48, 39]]], dtype=int8)

In [25]:
a.reshape(-1,3,5)

array([[[25, 22, 24, 13, 44],
        [17, 43, 21, 11, 34],
        [41, 33, 20, 40, 23]],

       [[37, 21, 35, 40, 13],
        [14, 19, 46, 28, 22],
        [14, 15, 48, 48, 39]]], dtype=int8)

In [26]:
a.ravel()

array([25, 22, 24, 13, 44, 17, 43, 21, 11, 34, 41, 33, 20, 40, 23, 37, 21,
       35, 40, 13, 14, 19, 46, 28, 22, 14, 15, 48, 48, 39], dtype=int8)

In [27]:
a.flatten()

array([25, 22, 24, 13, 44, 17, 43, 21, 11, 34, 41, 33, 20, 40, 23, 37, 21,
       35, 40, 13, 14, 19, 46, 28, 22, 14, 15, 48, 48, 39], dtype=int8)

In [54]:
b=np.random.randint(1,10,(2,3))
c=np.random.randint(1,10,(2,3))

In [55]:
b,c

(array([[2, 1, 6],
        [8, 6, 7]], dtype=int32),
 array([[8, 9, 6],
        [4, 6, 9]], dtype=int32))

**0>column wise >vstack**

**1>rowwise >hstack**

In [56]:
d=np.concatenate((b,c),axis=1)

In [57]:
d

array([[2, 1, 6, 8, 9, 6],
       [8, 6, 7, 4, 6, 9]], dtype=int32)

In [58]:
d=np.concatenate((b,c),axis=0)

In [59]:
d

array([[2, 1, 6],
       [8, 6, 7],
       [8, 9, 6],
       [4, 6, 9]], dtype=int32)

In [60]:
np.vstack((b,c))

array([[2, 1, 6],
       [8, 6, 7],
       [8, 9, 6],
       [4, 6, 9]], dtype=int32)

In [61]:
np.hstack((b,c))

array([[2, 1, 6, 8, 9, 6],
       [8, 6, 7, 4, 6, 9]], dtype=int32)

In [63]:
np.split(d, 2,axis =0)

[array([[2, 1, 6],
        [8, 6, 7]], dtype=int32),
 array([[8, 9, 6],
        [4, 6, 9]], dtype=int32)]

In [64]:
np.split(d, 1,axis =1)

[array([[2, 1, 6],
        [8, 6, 7],
        [8, 9, 6],
        [4, 6, 9]], dtype=int32)]

In [65]:
np.split(d, 3,axis =1)

[array([[2],
        [8],
        [8],
        [4]], dtype=int32),
 array([[1],
        [6],
        [9],
        [6]], dtype=int32),
 array([[6],
        [7],
        [6],
        [9]], dtype=int32)]