In [7]:
import numpy as np

In [10]:
a=np.array([[4,5,6],[5,7,9]])
b=np.array([[3,2,1],[5,4,6]])

In [11]:
a,b

(array([[4, 5, 6],
        [5, 7, 9]]),
 array([[3, 2, 1],
        [5, 4, 6]]))

## Arithmetic Operation ##

In [13]:
#a + b
np.add(a,b)

array([[ 7,  7,  7],
       [10, 11, 15]])

In [14]:
#a - b
np.subtract(a,b)

array([[1, 3, 5],
       [0, 3, 3]])

In [15]:
#a * b
np.multiply(a,b)

array([[12, 10,  6],
       [25, 28, 54]])

In [16]:
#a ** 2
#np.square(a)
np.power(a,2)

array([[16, 25, 36],
       [25, 49, 81]])

In [17]:
# a % b
np.divmod(a,b)

(array([[1, 2, 6],
        [1, 1, 1]]),
 array([[1, 1, 0],
        [0, 3, 3]]))

## Trignometric ##

In [20]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [-0.95892427,  0.6569866 ,  0.41211849]])

In [21]:
new= 1/np.tan(b)
new

array([[-7.01525255, -0.45765755,  0.64209262],
       [-0.29581292,  0.86369115, -3.436353  ]])

In [22]:
np.round(new, decimals=1)

array([[-7. , -0.5,  0.6],
       [-0.3,  0.9, -3.4]])

In [23]:
np.around(new, decimals=1)

array([[-7. , -0.5,  0.6],
       [-0.3,  0.9, -3.4]])