In [7]:
import numpy as np

In [10]:
a=np.array([[4,5,6],[5,7,9]])
b=np.array([[3,2,1],[5,4,6]])

In [11]:
a,b

(array([[4, 5, 6],
        [5, 7, 9]]),
 array([[3, 2, 1],
        [5, 4, 6]]))

## Arithmetic Operation ##

In [13]:
#a + b
np.add(a,b)

array([[ 7,  7,  7],
       [10, 11, 15]])

In [14]:
#a - b
np.subtract(a,b)

array([[1, 3, 5],
       [0, 3, 3]])

In [15]:
#a * b
np.multiply(a,b)

array([[12, 10,  6],
       [25, 28, 54]])

In [16]:
#a ** 2
#np.square(a)
np.power(a,2)

array([[16, 25, 36],
       [25, 49, 81]])

In [17]:
# a % b
np.divmod(a,b)

(array([[1, 2, 6],
        [1, 1, 1]]),
 array([[1, 1, 0],
        [0, 3, 3]]))

## Trignometric ##

In [20]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [-0.95892427,  0.6569866 ,  0.41211849]])

In [21]:
new= 1/np.tan(b)
new

array([[-7.01525255, -0.45765755,  0.64209262],
       [-0.29581292,  0.86369115, -3.436353  ]])

In [22]:
np.round(new, decimals=1)

array([[-7. , -0.5,  0.6],
       [-0.3,  0.9, -3.4]])

In [23]:
np.around(new, decimals=1)

array([[-7. , -0.5,  0.6],
       [-0.3,  0.9, -3.4]])

In [4]:
import numpy as np

In [14]:
a= np.array([[1,2,3],[4,5,6]])
b= np.random.randint(0,10,(3,3))


In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b


array([[9, 4, 0],
       [9, 8, 1],
       [6, 2, 1]], dtype=int32)

In [17]:
np.dot(a,b)

array([[ 45,  26,   5],
       [117,  68,  11]])

In [18]:
np.dot(b,a)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [19]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
np.trace(b)

np.int64(18)

In [21]:
#inverse of an array

In [22]:
np.linalg.det(b)

np.float64(41.999999999999986)

In [23]:
np.linalg.inv(b)

array([[ 0.14285714, -0.0952381 ,  0.0952381 ],
       [-0.07142857,  0.21428571, -0.21428571],
       [-0.71428571,  0.14285714,  0.85714286]])

In [25]:
np.dot(
    b, np.linalg.inv(b)
).round()

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [-0., -0.,  1.]])

## solve equation x+2y =1, 3x +5y=2 ##

In [34]:
c = np.array([[1,2],[3,5]])
d =np.array([1,2])

In [35]:
e =np.linalg.solve(c,d)

In [36]:
e

array([-1.,  1.])

In [37]:
np.dot(a,e)

array([1., 2.])

In [43]:
e=np.random.rand(90_00_000)
f=np.random.rand(90_00_000)


In [45]:
import time

In [48]:
# st=time.time()
# res=[]
# for _e, _f in zip(list(e),list(f)):
#     res.append(_e*_f)
# end=time.time()

In [47]:
print(end)

1753670019.0784423


In [52]:
st =time.time()
res= e*f
end=time.time()
print(f"time takein in sec:{end-st} ")

time takein in sec:0.057105064392089844 
