!pip install numpy --upgrade



In [2]:
import numpy as np

In [5]:
np.__version__

'2.3.1'

creating numpy array

In [13]:
list1= [[45,4,32]]

In [15]:
arr1=np.array(list1)

In [10]:
arr1

array([45,  4, 32])

In [16]:
arr1.shape

(1, 3)

In [17]:
arr1.ndim

2

In [18]:
list2=[[2,3,4],[6,7,8],[3,5,6]]
arr2=np.array(list2)

In [19]:
arr2


array([[2, 3, 4],
       [6, 7, 8],
       [3, 5, 6]])

In [20]:
arr2.shape


(3, 3)

In [21]:
arr2.ndim

2

In [24]:
np.zeros(shape=(4,4),dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
np.ones(shape=(6,6), dtype='int')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [28]:
np.full(shape=(3,4),fill_value=6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [31]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [32]:
np.linspace(1,10,num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [35]:
np.linspace((0,1,2),(10,20,30),num=20)


array([[ 0.        ,  1.        ,  2.        ],
       [ 0.52631579,  2.        ,  3.47368421],
       [ 1.05263158,  3.        ,  4.94736842],
       [ 1.57894737,  4.        ,  6.42105263],
       [ 2.10526316,  5.        ,  7.89473684],
       [ 2.63157895,  6.        ,  9.36842105],
       [ 3.15789474,  7.        , 10.84210526],
       [ 3.68421053,  8.        , 12.31578947],
       [ 4.21052632,  9.        , 13.78947368],
       [ 4.73684211, 10.        , 15.26315789],
       [ 5.26315789, 11.        , 16.73684211],
       [ 5.78947368, 12.        , 18.21052632],
       [ 6.31578947, 13.        , 19.68421053],
       [ 6.84210526, 14.        , 21.15789474],
       [ 7.36842105, 15.        , 22.63157895],
       [ 7.89473684, 16.        , 24.10526316],
       [ 8.42105263, 17.        , 25.57894737],
       [ 8.94736842, 18.        , 27.05263158],
       [ 9.47368421, 19.        , 28.52631579],
       [10.        , 20.        , 30.        ]])

In [36]:
np.random.randint(0,10,size=(2,2))

array([[7, 0],
       [9, 5]], dtype=int32)

In [4]:
np.ones(shape=(2,2,1,3),dtype= 'int8')

array([[[[1, 1, 1]],

        [[1, 1, 1]]],


       [[[1, 1, 1]],

        [[1, 1, 1]]]], dtype=int8)

In [5]:
a=np.array([1,2,3,4,5])

In [6]:
a[-3]

np.int64(3)

In [7]:
a[::-1]

array([5, 4, 3, 2, 1])

In [12]:
b= np.random.randint(0,10,size=(3,3))

In [13]:
b

array([[2, 9, 0],
       [3, 5, 4],
       [0, 9, 9]], dtype=int32)

In [10]:
b[1,1]

np.int32(6)

In [11]:
b[-1,0]

np.int32(0)

In [14]:
b[1:3,:2]

array([[3, 5],
       [0, 9]], dtype=int32)

In [15]:
b[1,:3]

array([3, 5, 4], dtype=int32)

In [16]:
b[1,]

array([3, 5, 4], dtype=int32)

In [17]:
b[1]

array([3, 5, 4], dtype=int32)

In [18]:
b[2]

array([0, 9, 9], dtype=int32)

In [19]:
b[:,2]

array([0, 4, 9], dtype=int32)

In [20]:
c=np.random.randint(0,25, size=(3,3,2))

In [21]:
c

array([[[17, 15],
        [ 4,  2],
        [17, 17]],

       [[17,  2],
        [18, 16],
        [21, 19]],

       [[20,  4],
        [14,  4],
        [10,  9]]], dtype=int32)

In [23]:
c[0][2,1]

np.int32(17)

In [24]:
c[0,2,1]

np.int32(17)

In [27]:
c[1][2,1]

np.int32(19)

In [29]:
c[2][1,1]

np.int32(4)

In [31]:
dataset=np.random.randint(0,100,(10000,25))

In [32]:
dataset

array([[96,  9, 96, ..., 42, 24, 80],
       [50, 70,  9, ..., 45, 71, 48],
       [46, 11, 23, ..., 78, 78, 13],
       ...,
       [34, 95, 32, ..., 34, 74, 18],
       [ 6, 86,  5, ..., 87, 18, 13],
       [41, 20, 48, ..., 83, 10, 84]], shape=(10000, 25), dtype=int32)

In [34]:
image_dataset=np.random.randint(0,100,(3,720,720))

In [35]:
image_dataset

array([[[97, 90, 73, ...,  2, 48, 81],
        [ 9, 52,  6, ..., 68, 16, 89],
        [57,  7, 90, ..., 64, 11, 25],
        ...,
        [96, 88, 37, ..., 82, 93, 40],
        [22, 29, 17, ..., 84, 39, 41],
        [75, 70, 63, ..., 40, 92, 73]],

       [[90, 48, 87, ..., 77, 98, 10],
        [75, 29, 12, ..., 14, 64, 65],
        [84,  0, 18, ..., 79, 81, 71],
        ...,
        [56, 86, 14, ..., 14, 93, 74],
        [62,  7, 70, ..., 98, 29, 94],
        [99,  4, 60, ..., 90, 70, 43]],

       [[64, 87, 96, ..., 10, 50, 91],
        [37, 66, 20, ...,  8, 16, 10],
        [97, 27, 42, ..., 80, 66, 50],
        ...,
        [38, 64, 44, ..., 39, 11, 37],
        [86, 19, 25, ..., 34,  5, 37],
        [28, 65, 19, ..., 18, 39, 27]]], shape=(3, 720, 720), dtype=int32)

In [41]:
image_dataset[1,:,:]

array([[90, 48, 87, ..., 77, 98, 10],
       [75, 29, 12, ..., 14, 64, 65],
       [84,  0, 18, ..., 79, 81, 71],
       ...,
       [56, 86, 14, ..., 14, 93, 74],
       [62,  7, 70, ..., 98, 29, 94],
       [99,  4, 60, ..., 90, 70, 43]], shape=(720, 720), dtype=int32)


boolean or mask indexing