In [1]:
import numpy as np

In [7]:
a=np.random.randint(10,50, size=(5,2,3),dtype='int8')

In [4]:
a.shape

(5, 2, 3)

In [5]:
a.ndim

3

In [8]:
a.dtype

dtype('int8')

In [9]:
a.size

30

In [10]:
(a.size *8)/8/1024 #number of elements

0.029296875

In [12]:
a.T


array([[[25, 43, 20, 40, 22],
        [13, 34, 37, 19, 48]],

       [[22, 21, 40, 13, 14],
        [44, 41, 21, 46, 48]],

       [[24, 11, 23, 14, 15],
        [17, 33, 35, 28, 39]]], dtype=int8)

In [13]:
a.shape

(5, 2, 3)

In [23]:
a.reshape(2,3,5)

array([[[25, 22, 24, 13, 44],
        [17, 43, 21, 11, 34],
        [41, 33, 20, 40, 23]],

       [[37, 21, 35, 40, 13],
        [14, 19, 46, 28, 22],
        [14, 15, 48, 48, 39]]], dtype=int8)

In [25]:
a.reshape(-1,3,5)

array([[[25, 22, 24, 13, 44],
        [17, 43, 21, 11, 34],
        [41, 33, 20, 40, 23]],

       [[37, 21, 35, 40, 13],
        [14, 19, 46, 28, 22],
        [14, 15, 48, 48, 39]]], dtype=int8)

In [26]:
a.ravel()

array([25, 22, 24, 13, 44, 17, 43, 21, 11, 34, 41, 33, 20, 40, 23, 37, 21,
       35, 40, 13, 14, 19, 46, 28, 22, 14, 15, 48, 48, 39], dtype=int8)

In [27]:
a.flatten()

array([25, 22, 24, 13, 44, 17, 43, 21, 11, 34, 41, 33, 20, 40, 23, 37, 21,
       35, 40, 13, 14, 19, 46, 28, 22, 14, 15, 48, 48, 39], dtype=int8)

In [54]:
b=np.random.randint(1,10,(2,3))
c=np.random.randint(1,10,(2,3))

In [55]:
b,c

(array([[2, 1, 6],
        [8, 6, 7]], dtype=int32),
 array([[8, 9, 6],
        [4, 6, 9]], dtype=int32))

**0>column wise >vstack**

**1>rowwise >hstack**

In [56]:
d=np.concatenate((b,c),axis=1)

In [57]:
d

array([[2, 1, 6, 8, 9, 6],
       [8, 6, 7, 4, 6, 9]], dtype=int32)

In [58]:
d=np.concatenate((b,c),axis=0)

In [59]:
d

array([[2, 1, 6],
       [8, 6, 7],
       [8, 9, 6],
       [4, 6, 9]], dtype=int32)

In [60]:
np.vstack((b,c))

array([[2, 1, 6],
       [8, 6, 7],
       [8, 9, 6],
       [4, 6, 9]], dtype=int32)

In [61]:
np.hstack((b,c))

array([[2, 1, 6, 8, 9, 6],
       [8, 6, 7, 4, 6, 9]], dtype=int32)

In [63]:
np.split(d, 2,axis =0)

[array([[2, 1, 6],
        [8, 6, 7]], dtype=int32),
 array([[8, 9, 6],
        [4, 6, 9]], dtype=int32)]

In [64]:
np.split(d, 1,axis =1)

[array([[2, 1, 6],
        [8, 6, 7],
        [8, 9, 6],
        [4, 6, 9]], dtype=int32)]

In [65]:
np.split(d, 3,axis =1)

[array([[2],
        [8],
        [8],
        [4]], dtype=int32),
 array([[1],
        [6],
        [9],
        [6]], dtype=int32),
 array([[6],
        [7],
        [6],
        [9]], dtype=int32)]

In [1]:
# How do you create a NumPy array from a Python list?

import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [4]:
# How do you create an array of all zeros or ones?

zeros = np.zeros((2, 3))  # 2x3 array of zeros
ones = np.ones((3, 2))    # 3x2 array of ones


In [3]:
#How do you reshape a NumPy array?
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [5]:
# How to find the shape and size of a NumPy array?
arr = np.array([[1, 2], [3, 4]])
print(arr.shape)  # Output: (2, 2)
print(arr.size)   # Output: 4


(2, 2)
4


In [6]:
# How do you perform element-wise operations?
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Output: [5 7 9]
print(a * b)  # Output: [ 4 10 18]


[5 7 9]
[ 4 10 18]


In [7]:
# How do you flatten a multi-dimensional array?
arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()
print(flat)  # Output: [1 2 3 4]


[1 2 3 4]


In [8]:
# How do you concatenate two arrays?
a = np.array([[1, 2]])
b = np.array([[3, 4]])
result = np.concatenate((a, b), axis=0)
print(result)



[[1 2]
 [3 4]]


In [9]:
# How do you get the maximum, minimum, and sum of a NumPy array?
arr = np.array([1, 2, 3, 4])
print(np.max(arr))  # Output: 4
print(np.min(arr))  # Output: 1
print(np.sum(arr))  # Output: 10


4
1
10


In [11]:
# **How do you get the index of the max/min element?**
arr = np.array([10, 20, 5, 30])
print(np.argmax(arr))  # Output: 3
print(np.argmin(arr))  # Output: 2


3
2


In [12]:
#How do you sort a NumPy array?
arr = np.array([3, 1, 4, 1, 5])
sorted_arr = np.sort(arr)
print(sorted_arr)


[1 1 3 4 5]


In [7]:
import numpy as np

In [8]:
z=np.random.randint(1,10,(4,6))

In [9]:
z.sum(axis=0)

array([13, 21, 18, 11, 25, 14])

In [11]:
z.prod(axis=0)

array([ 90, 576, 360,  30, 972,  75])

In [12]:
z.prod(axis=1)

array([ 2400,  1620,   810, 12960])

In [13]:
z.cumsum(axis=0)

array([[ 2,  4,  3,  5,  4,  5],
       [ 5,  7,  9,  7,  7, 10],
       [ 8, 13, 14,  8, 16, 11],
       [13, 21, 18, 11, 25, 14]])

In [14]:
z.min(axis=1)

array([2, 2, 1, 3], dtype=int32)

In [15]:
z.max(axis=1)

array([5, 6, 9, 9], dtype=int32)